from Ui_detecting import Ui_Detecting
from Ui_detecting import WIDTH as UI_DETECTING_WIDTH
from Ui_detecting import HEIGHT as UI_DETECTING_HEIGHT
from UI_Selecting import Ui_Selecting_Client
from UI_Selecting import WIDTH as UI_SELECTING_WIDTH
from UI_Selecting import HEIGHT as UI_SELECTING_HEIGHT
from UI_display_music_name import Ui_display_music_name
from UI_display_music_name import WIDTH as UI_DISPLAY_WIDTH
from UI_display_music_name import HEIGHT as UI_DISPLAY_HEIGHT