# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_detecting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
WIDTH=250
HEIGHT=90

class Ui_Detecting(object):
    def __setupUI(self,Widget:QtWidgets.QWidget):
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setEnabled(True)
        Widget.setSizePolicy(sizePolicy)
        Widget.setMinimumSize(QtCore.QSize(WIDTH, HEIGHT))
        Widget.setMaximumSize(QtCore.QSize(WIDTH, HEIGHT))
        Widget.setAcceptDrops(False)

    def setupUi(self, Detecting_Client:QtWidgets.QWidget,detect_text:str):
        Detecting_Client.setObjectName("Detecting_Client")
        self.__setupUI(Detecting_Client)
        self.__setupUI(Detecting_Client.parent())
        self.text = QtWidgets.QLabel(Detecting_Client)
        self.text.setGeometry(QtCore.QRect(10, 25, 220, 40))
        self.text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("AdLib WGL4 BT")
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.retranslateUi(Detecting_Client,detect_text)
        QtCore.QMetaObject.connectSlotsByName(Detecting_Client)

    def retranslateUi(self, Detecting_Client:QtWidgets.QWidget,detect_text:str):
        _translate = QtCore.QCoreApplication.translate
        Detecting_Client.setWindowTitle(_translate("dectecting", "Youtube Title Displayer"))
        self.text.setText(_translate("Detecting_Client", "偵測{}視窗標題中...").format(detect_text))
