# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_detecting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
WIDTH=250
HEIGHT=90

class Ui_Detecting(object):
    def setupUi(self, Detecting_Client:QtWidgets.QMainWindow,detect_text:str):
        Detecting_Client.setObjectName("Detecting_Client")
        Detecting_Client.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Detecting_Client.sizePolicy().hasHeightForWidth())
        Detecting_Client.setSizePolicy(sizePolicy)
        Detecting_Client.setMinimumSize(QtCore.QSize(WIDTH, HEIGHT))
        Detecting_Client.setMaximumSize(QtCore.QSize(WIDTH, HEIGHT))
        Detecting_Client.setAcceptDrops(False)
        self.text = QtWidgets.QLabel(Detecting_Client)
        self.text.setGeometry(QtCore.QRect(10, 25, 220, 40))
        self.text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("AdLib WGL4 BT")
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setObjectName("text")
        

        self.retranslateUi(Detecting_Client,detect_text)
        QtCore.QMetaObject.connectSlotsByName(Detecting_Client)
    
    def MainWindowsetup(self,MainWindow:QtWidgets.QStackedWidget):
        MainWindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(WIDTH, HEIGHT))
        MainWindow.setMaximumSize(QtCore.QSize(WIDTH, HEIGHT))
        MainWindow.setAcceptDrops(False)

    def retranslateUi(self, Detecting_Client:QtWidgets.QWidget,detect_text:str):
        _translate = QtCore.QCoreApplication.translate
        Detecting_Client.setWindowTitle(_translate("dectecting", "Youtube Title Displayer"))
        self.text.setText(_translate("Detecting_Client", "偵測{}視窗標題中...").format(detect_text))
