# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_titlefilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

WIDTH=568
HEIGHT=66
class Ui_titlefilter(object):
    def __setupUI(self,Widget:QtWidgets.QWidget):
        Widget.resize(WIDTH,HEIGHT)
        Widget.setMinimumSize(QtCore.QSize(WIDTH, HEIGHT))
        Widget.setMaximumSize(QtCore.QSize(WIDTH, HEIGHT))
    
    def setupUi(self, UI_titlefilter:QtWidgets.QWidget):
        UI_titlefilter.setObjectName("UI_titlefilter")
        self.__setupUI(UI_titlefilter)
        self.__setupUI(UI_titlefilter.parent())
        self.titleEdit = QtWidgets.QTextEdit(UI_titlefilter)
        self.titleEdit.setGeometry(QtCore.QRect(10, 30, 471, 21))
        self.titleEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.titleEdit.setSizeAdjustPolicy(QtWidgets.QTextEdit.SizeAdjustPolicy.AdjustIgnored)
        self.titleEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.titleEdit.setObjectName("titleEdit")
        self.Enter = QtWidgets.QPushButton(UI_titlefilter)
        self.Enter.setGeometry(QtCore.QRect(490, 30, 71, 23))
        self.Enter.setObjectName("Enter")
        self.textlabel = QtWidgets.QLabel(UI_titlefilter)
        self.textlabel.setGeometry(QtCore.QRect(10, 5, 461, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.textlabel.setFont(font)
        self.textlabel.setObjectName("textlabel")

        self.retranslateUi(UI_titlefilter)
        QtCore.QMetaObject.connectSlotsByName(UI_titlefilter)

    def retranslateUi(self, UI_titlefilter):
        _translate = QtCore.QCoreApplication.translate
        # UI_titlefilter.setWindowTitle(_translate("UI_titlefilter", "Form"))
        self.Enter.setText(_translate("UI_titlefilter", "確認"))
        self.textlabel.setText(_translate("UI_titlefilter", "請把要顯示的標題保留下來(滑鼠指我顯示更多資訊)"))
        self.textlabel.setToolTip(_translate("UI_titlefilter", 
                                             '例如有視窗標題為"AAA BBBSSS歌名 - VLC 媒體播放器"\n而您想顯示"BBBSSS歌名"，則請只將"BBBSSS歌名"留下。\n\
                                              請注意，無法顯示 "AAA 歌名" 或者 "BBB歌名"'))
