# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_titlelist.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icon
WIDTH=400
HEIGHT=300
class Ui_titlelist(object):
    def __setupUI(self,Widget:QtWidgets.QWidget):
        Widget.resize(WIDTH,HEIGHT)
        Widget.setMinimumSize(QtCore.QSize(WIDTH, HEIGHT))
        Widget.setMaximumSize(QtCore.QSize(WIDTH, HEIGHT))

    def setupUi(self, UI_titlelist:QtWidgets.QWidget):
        UI_titlelist.setObjectName("UI_titilelist")
        self.__setupUI(UI_titlelist)
        self.__setupUI(UI_titlelist.parent())
        self.titlelist = QtWidgets.QListWidget(UI_titlelist)
        self.titlelist.setGeometry(QtCore.QRect(10, 30, 381, 231))
        self.titlelist.setProperty("isWrapping", False)
        self.titlelist.setObjectName("titlelist")
        self.OK = QtWidgets.QPushButton(UI_titlelist)
        self.OK.setGeometry(QtCore.QRect(160, 270, 81, 23))
        self.OK.setObjectName("OK")
        self.textlabel = QtWidgets.QLabel(UI_titlelist)
        self.textlabel.setGeometry(QtCore.QRect(10, 10, 371, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.textlabel.setFont(font)
        self.textlabel.setObjectName("textlabel")
        self.refresh = QtWidgets.QPushButton(UI_titlelist)
        self.refresh.setGeometry(QtCore.QRect(10, 267, 26, 26))
        self.refresh.setText("")
        pm = QtGui.QPixmap()
        pm.loadFromData(icon.b64decode(icon.refreshicon))
        i = QtGui.QIcon()
        i.addPixmap(pm)
        self.refresh.setIcon(i)
        # self.refresh.setIcon(UI_titlelist.style().standardIcon(QtWidgets.QStyle.StandardPixmap.SP_BrowserReload))
        self.refresh.setObjectName("refresh")

        self.retranslateUi(UI_titlelist)
        QtCore.QMetaObject.connectSlotsByName(UI_titlelist)

    def retranslateUi(self, UI_titilelist:QtWidgets.QWidget):
        _translate = QtCore.QCoreApplication.translate
        # UI_titilelist.setWindowTitle(_translate("UI_titilelist", "Form"))
        self.titlelist.setSortingEnabled(True)
        self.OK.setText(_translate("UI_titilelist", "確認"))
        self.textlabel.setText(_translate("UI_titilelist", "請選擇要偵測的視窗之標題。"))
